name: "Build NH"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "xtask/Cargo.toml"
      - "src/**"
      - "xtask/src/**"
      - ".cargo/**"
      - ".github/workflows/build.yaml"
  push:
    branches-ignore:
      - "update-*"
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "xtask/Cargo.toml"
      - "src/**"
      - "xtask/src/**"
      - ".cargo/**"
      - ".github/workflows/build.yaml"

jobs:
  build-linux:
    name: "Build NH on Linux"
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@master
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - run: nix build -L --no-link
        name: Build

  build-darwin:
    name: "Build NH on Darwin"
    runs-on: macos-latest

    steps:
      - uses: cachix/install-nix-action@master
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Build NH with Nix
        run: nix build -L --no-link
