name: "Update NH"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: cachix/install-nix-action@master
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v5
      name: Checkout

    - name: Update
      run: |
        nix flake update
        eval "$(nix print-dev-env)"
        cargo update
        ./fix.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: '${{ secrets.PAT }}'
        title: "build: bump dependencies"
        committer: GitHub <noreply@github.com>
        author: GitHub <noreply@github.com>
        commit-message: |
          build: bump dependencies

          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: update
        # branch-suffix: timestamp
        delete-branch: true
